In [1]:
import numpy as np
import pandas as pd

from sklearn.model_selection import KFold, cross_val_score
from sklearn.linear_model import LinearRegression
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import OneHotEncoder, StandardScaler, OrdinalEncoder
from sklearn.compose import ColumnTransformer
from sklearn.svm import SVR

from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_absolute_error

from sklearn.decomposition import PCA

In [3]:
from sklearn.linear_model import LinearRegression, Ridge, Lasso
from sklearn.svm import SVR
from sklearn.tree import DecisionTreeRegressor
from sklearn.ensemble import (
    RandomForestRegressor,
    ExtraTreesRegressor,
    GradientBoostingRegressor,
    AdaBoostRegressor

)
from sklearn.neural_network import MLPRegressor
from xgboost import XGBRegressor

In [5]:
df = pd.read_csv('gurgaon_properties_post_feature_selection_v2.csv')

In [7]:
df.head()

,property_type,sector,price,bedRoom,bathroom,balcony,agePossession,built_up_area,servant room,store room,furnishing_type,luxury_category,floor_category
0,flat,sector 36,0.82,3.0,2.0,2,New Property,850.0,0.0,0.0,0.0,Low,Low Floor
1,flat,sector 89,0.95,2.0,2.0,2,New Property,1226.0,1.0,0.0,0.0,Low,Mid Floor
2,flat,sohna road,0.32,2.0,2.0,1,New Property,1000.0,0.0,0.0,0.0,Low,High Floor
3,flat,sector 92,1.60,3.0,4.0,3+,Relatively New,1615.0,1.0,0.0,1.0,High,Mid Floor
4,flat,sector 102,0.48,2.0,2.0,1,Relatively New,582.0,0.0,1.0,0.0,High,Mid Floor

In [9]:
df['furnishing_type'].value_counts()

furnishing_type
0.0    2349
1.0    1018
2.0     187
Name: count, dtype: int64

In [11]:
# 0 -> unfurnished
# 1 -> semifurnished
# 2 -> furnished
df['furnishing_type'] = df['furnishing_type'].replace({0.0:'unfurnished',1.0:'semifurnished',2.0:'furnished'})

In [13]:
df.head()

,property_type,sector,price,bedRoom,bathroom,balcony,agePossession,built_up_area,servant room,store room,furnishing_type,luxury_category,floor_category
0,flat,sector 36,0.82,3.0,2.0,2,New Property,850.0,0.0,0.0,unfurnished,Low,Low Floor
1,flat,sector 89,0.95,2.0,2.0,2,New Property,1226.0,1.0,0.0,unfurnished,Low,Mid Floor
2,flat,sohna road,0.32,2.0,2.0,1,New Property,1000.0,0.0,0.0,unfurnished,Low,High Floor
3,flat,sector 92,1.60,3.0,4.0,3+,Relatively New,1615.0,1.0,0.0,semifurnished,High,Mid Floor
4,flat,sector 102,0.48,2.0,2.0,1,Relatively New,582.0,0.0,1.0,unfurnished,High,Mid Floor

In [15]:
X = df.drop(columns=['price'])
y = df['price']

In [17]:
# Applying the log1p transformation to the target variable
y_transformed = np.log1p(y)

### Ordinal Encoding

In [212]:
columns_to_encode = ['property_type','sector', 'balcony', 'agePossession', 'furnishing_type', 'luxury_category', 'floor_category']

In [214]:
# Creating a column transformer for preprocessing
preprocessor = ColumnTransformer(
    transformers=[
        ('num', StandardScaler(), ['bedRoom', 'bathroom', 'built_up_area', 'servant room', 'store room']),
        ('ca t', OrdinalEncoder(), columns_to_encode)
    ],
    remainder='passthrough'
)

In [216]:
# Creating a pipeline
pipeline = Pipeline([
    ('preprocessor', preprocessor),
    ('regressor', LinearRegression())
])

In [218]:
# K-fold cross-validation
kfold = KFold(n_splits=10, shuffle=True, random_state=42)
scores = cross_val_score(pipeline, X, y_transformed, cv=kfold, scoring='r2')

In [220]:
scores.mean(),scores.std()

(np.float64(0.7363096633436828), np.float64(0.03238005754429932))

In [30]:
X_train, X_test, y_train, y_test = train_test_split(X,y_transformed,test_size=0.2,random_state=42)

In [32]:
pipeline.fit(X_train,y_train)

Pipeline(steps=[('preprocessor',
                 ColumnTransformer(remainder='passthrough',
                                   transformers=[('num', StandardScaler(),
                                                  ['bedRoom', 'bathroom',
                                                   'built_up_area',
                                                   'servant room',
                                                   'store room']),
                                                 ('ca t', OrdinalEncoder(),
                                                  ['property_type', 'sector',
                                                   'balcony', 'agePossession',
                                                   'furnishing_type',
                                                   'luxury_category',
                                                   'floor_category'])])),
                ('regressor', LinearRegression())])

In [34]:
y_pred = pipeline.predict(X_test)

In [36]:
y_pred = np.expm1(y_pred)

In [38]:
mean_absolute_error(np.expm1(y_test),y_pred)

0.9463822160089367

In [40]:
# created a fuction this function will only need model name

def scorer(model_name, model):

    output = []

    output.append(model_name)

    pipeline = Pipeline([
        ('preprocessor', preprocessor),
        ('regressor', model)
    ])

    # K-fold cross-validation
    kfold = KFold(n_splits=10, shuffle=True, random_state=42)
    scores = cross_val_score(pipeline, X, y_transformed, cv=kfold, scoring='r2')

    output.append(scores.mean())

    X_train, X_test, y_train, y_test = train_test_split(X,y_transformed,test_size=0.2,random_state=42)

    pipeline.fit(X_train,y_train)

    y_pred = pipeline.predict(X_test)

    y_pred = np.expm1(y_pred)

    output.append(mean_absolute_error(np.expm1(y_test),y_pred))

    return output

In [42]:
model_dict = {
    'linear_reg':LinearRegression(),
    'svr':SVR(),
    'ridge':Ridge(),
    'LASSO':Lasso(),
    'decision tree': DecisionTreeRegressor(),
    'random forest':RandomForestRegressor(),
    'extra trees': ExtraTreesRegressor(),
    'gradient boosting': GradientBoostingRegressor(),
    'adaboost': AdaBoostRegressor(),
    'mlp': MLPRegressor(),
    'xgboost':XGBRegressor()
}

In [44]:
model_output = []
for model_name,model in model_dict.items():
    model_output.append(scorer(model_name, model))

In [45]:
model_output

[['linear_reg', np.float64(0.7363096633436828), 0.9463822160089367],
 ['svr', np.float64(0.7642079133544133), 0.8472636473483927],
 ['ridge', np.float64(0.7363125343993553), 0.946338774185338],
 ['LASSO', np.float64(0.05943378064493573), 1.5289059868927528],
 ['decision tree', np.float64(0.772952575944894), 0.7539467766404448],
 ['random forest', np.float64(0.8810887691100522), 0.525101786830047],
 ['extra trees', np.float64(0.868439746615496), 0.5565424162996464],
 ['gradient boosting', np.float64(0.8725454429456285), 0.5764744395093],
 ['adaboost', np.float64(0.7557252867991301), 0.827907262913805],
 ['mlp', np.float64(0.8099026432052071), 0.7135466342087204],
 ['xgboost', np.float64(0.8894876835260124), 0.5040475180464287]]

In [48]:
model_df = pd.DataFrame(model_output, columns=['name','r2','mae'])

In [50]:
model_df.sort_values(['mae'])

                 name        r2       mae
10            xgboost  0.889488  0.504048
5       random forest  0.881089  0.525102
6         extra trees  0.868440  0.556542
7   gradient boosting  0.872545  0.576474
9                 mlp  0.809903  0.713547
4       decision tree  0.772953  0.753947
8            adaboost  0.755725  0.827907
1                 svr  0.764208  0.847264
2               ridge  0.736313  0.946339
0          linear_reg  0.736310  0.946382
3               LASSO  0.059434  1.528906

### OneHotEncoding

In [52]:
# Creating a column transformer for preprocessing
preprocessor = ColumnTransformer(
    transformers=[
        ('num', StandardScaler(), ['bedRoom', 'bathroom', 'built_up_area', 'servant room', 'store room']),
        ('cat', OrdinalEncoder(), columns_to_encode),
        ('cat1',OneHotEncoder(drop='first'),['sector','agePossession','furnishing_type'])
    ],
    remainder='passthrough'
)

In [ ]:
# Creating a pipeline
pipeline = Pipeline([
    ('preprocessor', preprocessor),
    ('regressor', LinearRegression())
])

In [54]:
# K-fold cross-validation
kfold = KFold(n_splits=10, shuffle=True, random_state=42)
scores = cross_val_score(pipeline, X, y_transformed, cv=kfold, scoring='r2')

In [56]:
scores.mean()

np.float64(0.7363096633436828)

In [58]:
scores.std()

np.float64(0.03238005754429932)

In [60]:
X_train, X_test, y_train, y_test = train_test_split(X,y_transformed,test_size=0.2,random_state=42)

In [62]:
pipeline.fit(X_train,y_train)

Pipeline(steps=[('preprocessor',
                 ColumnTransformer(remainder='passthrough',
                                   transformers=[('num', StandardScaler(),
                                                  ['bedRoom', 'bathroom',
                                                   'built_up_area',
                                                   'servant room',
                                                   'store room']),
                                                 ('ca t', OrdinalEncoder(),
                                                  ['property_type', 'sector',
                                                   'balcony', 'agePossession',
                                                   'furnishing_type',
                                                   'luxury_category',
                                                   'floor_category'])])),
                ('regressor', LinearRegression())])

In [64]:
y_pred = pipeline.predict(X_test)

In [66]:
y_pred = np.expm1(y_pred)

In [68]:
mean_absolute_error(np.expm1(y_test),y_pred)

0.9463822160089367

In [70]:
def scorer(model_name, model):

    output = []

    output.append(model_name)

    pipeline = Pipeline([
        ('preprocessor', preprocessor),
        ('regressor', model)
    ])

    # K-fold cross-validation
    kfold = KFold(n_splits=10, shuffle=True, random_state=42)
    scores = cross_val_score(pipeline, X, y_transformed, cv=kfold, scoring='r2')

    output.append(scores.mean())

    X_train, X_test, y_train, y_test = train_test_split(X,y_transformed,test_size=0.2,random_state=42)

    pipeline.fit(X_train,y_train)

    y_pred = pipeline.predict(X_test)

    y_pred = np.expm1(y_pred)

    output.append(mean_absolute_error(np.expm1(y_test),y_pred))

    return output

In [72]:
model_dict = {
    'linear_reg':LinearRegression(),
    'svr':SVR(),
    'ridge':Ridge(),
    'LASSO':Lasso(),
    'decision tree': DecisionTreeRegressor(),
    'random forest':RandomForestRegressor(),
    'extra trees': ExtraTreesRegressor(),
    'gradient boosting': GradientBoostingRegressor(),
    'adaboost': AdaBoostRegressor(),
    'mlp': MLPRegressor(),
    'xgboost':XGBRegressor()
}

In [74]:
model_output = []
for model_name,model in model_dict.items():
    model_output.append(scorer(model_name, model))

In [76]:
model_df = pd.DataFrame(model_output, columns=['name','r2','mae'])

In [78]:
model_df.sort_values(['mae'])

                 name        r2       mae
6         extra trees  0.893775  0.467848
10            xgboost  0.895850  0.493456
5       random forest  0.890943  0.495962
7   gradient boosting  0.876651  0.569723
9                 mlp  0.874629  0.573279
0          linear_reg  0.854614  0.649743
2               ridge  0.854686  0.652804
4       decision tree  0.809453  0.702767
1                 svr  0.769741  0.834124
8            adaboost  0.753835  0.844655
3               LASSO  0.059434  1.528906

### OneHotEncoding With PCA

In [80]:
# Creating a column transformer for preprocessing
preprocessor = ColumnTransformer(
    transformers=[
        ('num', StandardScaler(), ['bedRoom', 'bathroom', 'built_up_area', 'servant room', 'store room']),
        ('cat', OrdinalEncoder(), columns_to_encode),
        ('cat1',OneHotEncoder(drop='first',sparse_output=False),['sector','agePossession'])
    ],
    remainder='passthrough'
)

In [82]:
 # Creating a pipeline
pipeline = Pipeline([
    ('preprocessor', preprocessor),
    ('pca', PCA(n_components=0.95)),
    ('regressor', LinearRegression())
])

In [84]:
# K-fold cross-validation
kfold = KFold(n_splits=10, shuffle=True, random_state=42)
scores = cross_val_score(pipeline, X, y_transformed, cv=kfold, scoring='r2')

In [86]:
scores.mean()

np.float64(0.0622520143145114)

In [88]:
scores.std()

np.float64(0.019860594071640075)

In [90]:
def scorer(model_name, model):

    output = []

    output.append(model_name)

    pipeline = Pipeline([
        ('preprocessor', preprocessor),
        ('pca', PCA(n_components=0.95)),
        ('regressor', model)
    ])

    # K-fold cross-validation
    kfold = KFold(n_splits=10, shuffle=True, random_state=42)
    scores = cross_val_score(pipeline, X, y_transformed, cv=kfold, scoring='r2')

    output.append(scores.mean())

    X_train, X_test, y_train, y_test = train_test_split(X,y_transformed,test_size=0.2,random_state=42)

    pipeline.fit(X_train,y_train)

    y_pred = pipeline.predict(X_test)

    y_pred = np.expm1(y_pred)

    output.append(mean_absolute_error(np.expm1(y_test),y_pred))

    return output

In [92]:
model_dict = {
    'linear_reg':LinearRegression(),
    'svr':SVR(),
    'ridge':Ridge(),
    'LASSO':Lasso(),
    'decision tree': DecisionTreeRegressor(),
    'random forest':RandomForestRegressor(),
    'extra trees': ExtraTreesRegressor(),
    'gradient boosting': GradientBoostingRegressor(),
    'adaboost': AdaBoostRegressor(),
    'mlp': MLPRegressor(),
    'xgboost':XGBRegressor()
}

In [94]:
model_output = []
for model_name,model in model_dict.items():
    model_output.append(scorer(model_name, model))

In [96]:
model_df = pd.DataFrame(model_output, columns=['name','r2','mae'])

In [98]:
model_df.sort_values(['mae'])

                 name        r2       mae
5       random forest  0.763661  0.657327
6         extra trees  0.740415  0.696993
4       decision tree  0.696442  0.761509
10            xgboost  0.622205  0.967581
7   gradient boosting  0.610623  0.987906
8            adaboost  0.311332  1.335629
1                 svr  0.218045  1.361141
9                 mlp  0.198511  1.401098
2               ridge  0.062252  1.526707
0          linear_reg  0.062252  1.526707
3               LASSO  0.059676  1.528739

### Target Encoder

In [100]:
pip install category-encoders

Collecting category-encoders
  Downloading category_encoders-2.9.0-py3-none-any.whl.metadata (7.9 kB)
Requirement already satisfied: numpy>=1.14.0 in /opt/anaconda3/envs/py311_clean/lib/python3.11/site-packages (from category-encoders) (2.3.5)
Requirement already satisfied: pandas>=1.0.5 in /opt/anaconda3/envs/py311_clean/lib/python3.11/site-packages (from category-encoders) (2.3.3)
Requirement already satisfied: patsy>=0.5.1 in /opt/anaconda3/envs/py311_clean/lib/python3.11/site-packages (from category-encoders) (1.0.2)
Requirement already satisfied: scikit-learn>=1.6.0 in /opt/anaconda3/envs/py311_clean/lib/python3.11/site-packages (from category-encoders) (1.8.0)
Requirement already satisfied: scipy>=1.0.0 in /opt/anaconda3/envs/py311_clean/lib/python3.11/site-packages (from category-encoders) (1.16.3)
Requirement already satisfied: statsmodels>=0.9.0 in /opt/anaconda3/envs/py311_clean/lib/python3.11/site-packages (from category-encoders) (0.14.6)
Requirement already satisfied: python-dateutil>=2.8.2 in /opt/anaconda3/envs/py311_clean/lib/python3.11/site-packages (from pandas>=1.0.5->category-encoders) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /opt/anaconda3/envs/py311_clean/lib/python3.11/site-packages (from pandas>=1.0.5->category-encoders) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /opt/anaconda3/envs/py311_clean/lib/python3.11/site-packages (from pandas>=1.0.5->category-encoders) (2025.3)
Requirement already satisfied: six>=1.5 in /opt/anaconda3/envs/py311_clean/lib/python3.11/site-packages (from python-dateutil>=2.8.2->pandas>=1.0.5->category-encoders) (1.17.0)
Requirement already satisfied: joblib>=1.3.0 in /opt/anaconda3/envs/py311_clean/lib/python3.11/site-packages (from scikit-learn>=1.6.0->category-encoders) (1.5.3)
Requirement already satisfied: threadpoolctl>=3.2.0 in /opt/anaconda3/envs/py311_clean/lib/python3.11/site-packages (from scikit-learn>=1.6.0->category-encoders) (3.6.0)
Requirement already satisfied: packaging>=21.3 in /opt/anaconda3/envs/py311_clean/lib/python3.11/site-packages (from statsmodels>=0.9.0->category-encoders) (25.0)
Downloading category_encoders-2.9.0-py3-none-any.whl (85 kB)
Installing collected packages: category-encoders
Successfully installed category-encoders-2.9.0
Note: you may need to restart the kernel to use updated packages.

In [102]:
# @title Default title text
import category_encoders as ce

columns_to_encode = ['property_type','sector', 'balcony', 'agePossession', 'furnishing_type', 'luxury_category', 'floor_category']

# Creating a column transformer for preprocessing
preprocessor = ColumnTransformer(
    transformers=[
        ('num', StandardScaler(), ['bedRoom', 'bathroom', 'built_up_area', 'servant room', 'store room']),
        ('cat', OrdinalEncoder(), columns_to_encode),
        ('cat1',OneHotEncoder(drop='first',sparse_output=False),['agePossession']),
        ('target_enc', ce.TargetEncoder(), ['sector'])
    ],
    remainder='passthrough'
)

In [104]:
 # Creating a pipeline
pipeline = Pipeline([
    ('preprocessor', preprocessor),
    ('regressor', LinearRegression())
])

In [106]:
# K-fold cross-validation
kfold = KFold(n_splits=10, shuffle=True, random_state=42)
scores = cross_val_score(pipeline, X, y_transformed, cv=kfold, scoring='r2')

In [108]:
scores.mean(),scores.std()

(np.float64(0.829521918225536), np.float64(0.018384463379122813))

In [110]:
def scorer(model_name, model):

    output = []

    output.append(model_name)

    pipeline = Pipeline([
        ('preprocessor', preprocessor),
        ('regressor', model)
    ])

    # K-fold cross-validation
    kfold = KFold(n_splits=10, shuffle=True, random_state=42)
    scores = cross_val_score(pipeline, X, y_transformed, cv=kfold, scoring='r2')

    output.append(scores.mean())

    X_train, X_test, y_train, y_test = train_test_split(X,y_transformed,test_size=0.2,random_state=42)

    pipeline.fit(X_train,y_train)

    y_pred = pipeline.predict(X_test)

    y_pred = np.expm1(y_pred)

    output.append(mean_absolute_error(np.expm1(y_test),y_pred))

    return output

In [112]:
model_dict = {
    'linear_reg':LinearRegression(),
    'svr':SVR(),
    'ridge':Ridge(),
    'LASSO':Lasso(),
    'decision tree': DecisionTreeRegressor(),
    'random forest':RandomForestRegressor(),
    'extra trees': ExtraTreesRegressor(),
    'gradient boosting': GradientBoostingRegressor(),
    'adaboost': AdaBoostRegressor(),
    'mlp': MLPRegressor(),
    'xgboost':XGBRegressor()
}

In [114]:
model_output = []
for model_name,model in model_dict.items():
    model_output.append(scorer(model_name, model))

In [116]:
model_df = pd.DataFrame(model_output, columns=['name','r2','mae'])

In [118]:
model_df.sort_values(['mae'])

                 name        r2       mae
6         extra trees  0.902866  0.445411
10            xgboost  0.904798  0.447518
5       random forest  0.901063  0.458104
7   gradient boosting  0.889197  0.510053
4       decision tree  0.827580  0.549771
9                 mlp  0.852179  0.593871
8            adaboost  0.816215  0.692756
0          linear_reg  0.829522  0.713011
2               ridge  0.829536  0.713523
1                 svr  0.782917  0.818851
3               LASSO  0.059434  1.528906

### Hyperparameter Tuning

In [120]:
from sklearn.model_selection import GridSearchCV

In [122]:
param_grid = {
    'regressor__n_estimators': [50, 100, 200, 300],
    'regressor__max_depth': [None, 10, 20, 30],
    'regressor__max_samples':[0.1, 0.25, 0.5, 1.0],
    'regressor__max_features': ['auto', 'sqrt']
}

In [124]:
columns_to_encode = ['property_type','sector', 'balcony', 'agePossession', 'furnishing_type', 'luxury_category', 'floor_category']

# Creating a column transformer for preprocessing
preprocessor = ColumnTransformer(
    transformers=[
        ('num', StandardScaler(), ['bedRoom', 'bathroom', 'built_up_area', 'servant room', 'store room']),
        ('cat', OrdinalEncoder(), columns_to_encode),
        ('cat1',OneHotEncoder(drop='first',sparse_output=False),['agePossession']),
        ('target_enc', ce.TargetEncoder(), ['sector'])
    ],
    remainder='passthrough'
)

In [126]:
pipeline = Pipeline([
    ('preprocessor', preprocessor),
    ('regressor', RandomForestRegressor())
])

In [128]:
kfold = KFold(n_splits=10, shuffle=True, random_state=42)

In [130]:
search = GridSearchCV(pipeline, param_grid, cv=kfold, scoring='r2', n_jobs=-1, verbose=4)

In [132]:
search.fit(X, y_transformed)

Fitting 10 folds for each of 128 candidates, totalling 1280 fits
[CV 1/10] END regressor__max_depth=None, regressor__max_features=auto, regressor__max_samples=0.1, regressor__n_estimators=50;, score=nan total time=   0.0s
[CV 6/10] END regressor__max_depth=None, regressor__max_features=auto, regressor__max_samples=0.1, regressor__n_estimators=100;, score=nan total time=   0.0s
[CV 1/10] END regressor__max_depth=None, regressor__max_features=auto, regressor__max_samples=0.1, regressor__n_estimators=200;, score=nan total time=   0.0s
[CV 7/10] END regressor__max_depth=None, regressor__max_features=auto, regressor__max_samples=0.1, regressor__n_estimators=200;, score=nan total time=   0.0s
[CV 7/10] END regressor__max_depth=None, regressor__max_features=auto, regressor__max_samples=0.1, regressor__n_estimators=300;, score=nan total time=   0.0s
[CV 1/10] END regressor__max_depth=None, regressor__max_features=auto, regressor__max_samples=0.25, regressor__n_estimators=50;, score=nan total time=   0.0s
[CV 7/10] END regressor__max_depth=None, regressor__max_features=auto, regressor__max_samples=0.25, regressor__n_estimators=50;, score=nan total time=   0.0s
[CV 7/10] END regressor__max_depth=None, regressor__max_features=auto, regressor__max_samples=0.25, regressor__n_estimators=100;, score=nan total time=   0.0s
[CV 8/10] END regressor__max_depth=None, regressor__max_features=auto, regressor__max_samples=0.25, regressor__n_estimators=100;, score=nan total time=   0.0s
[CV 9/10] END regressor__max_depth=None, regressor__max_features=auto, regressor__max_samples=0.25, regressor__n_estimators=300;, score=nan total time=   0.0s
[CV 10/10] END regressor__max_depth=None, regressor__max_features=auto, regressor__max_samples=0.25, regressor__n_estimators=300;, score=nan total time=   0.0s
[CV 9/10] END regressor__max_depth=None, regressor__max_features=auto, regressor__max_samples=0.5, regressor__n_estimators=200;, score=nan total time=   0.0s
[CV 10/10] END regressor__max_depth=None, regressor__max_features=auto, regressor__max_samples=0.5, regressor__n_estimators=200;, score=nan total time=   0.0s
[CV 1/10] END regressor__max_depth=None, regressor__max_features=auto, regressor__max_samples=0.5, regressor__n_estimators=300;, score=nan total time=   0.0s
[CV 2/10] END regressor__max_depth=None, regressor__max_features=auto, regressor__max_samples=0.5, regressor__n_estimators=300;, score=nan total time=   0.0s
[CV 5/10] END regressor__max_depth=None, regressor__max_features=auto, regressor__max_samples=1.0, regressor__n_estimators=50;, score=nan total time=   0.0s
[CV 6/10] END regressor__max_depth=None, regressor__max_features=auto, regressor__max_samples=1.0, regressor__n_estimators=50;, score=nan total time=   0.0s
[CV 7/10] END regressor__max_depth=None, regressor__max_features=auto, regressor__max_samples=1.0, regressor__n_estimators=50;, score=nan total time=   0.0s
[CV 8/10] END regressor__max_depth=None, regressor__max_features=auto, regressor__max_samples=1.0, regressor__n_estimators=50;, score=nan total time=   0.0s
[CV 3/10] END regressor__max_depth=None, regressor__max_features=auto, regressor__max_samples=1.0, regressor__n_estimators=300;, score=nan total time=   0.0s
[CV 4/10] END regressor__max_depth=None, regressor__max_features=auto, regressor__max_samples=1.0, regressor__n_estimators=300;, score=nan total time=   0.0s
[CV 5/10] END regressor__max_depth=None, regressor__max_features=auto, regressor__max_samples=1.0, regressor__n_estimators=300;, score=nan total time=   0.0s
[CV 6/10] END regressor__max_depth=None, regressor__max_features=auto, regressor__max_samples=1.0, regressor__n_estimators=300;, score=nan total time=   0.0s
[CV 7/10] END regressor__max_depth=None, regressor__max_features=auto, regressor__max_samples=1.0, regressor__n_estimators=300;, score=nan total time=   0.0s
[CV 8/10] END regressor__max_depth=None, regressor__max_features=auto, regressor__max_samples=1.0, regressor__n_estimators=300;, score=nan total time=   0.0s
[CV 9/10] END regressor__max_depth=None, regressor__max_features=auto, regressor__max_samples=1.0, regressor__n_estimators=300;, score=nan total time=   0.0s
[CV 10/10] END regressor__max_depth=None, regressor__max_features=auto, regressor__max_samples=1.0, regressor__n_estimators=300;, score=nan total time=   0.0s
[CV 9/10] END regressor__max_depth=None, regressor__max_features=sqrt, regressor__max_samples=0.25, regressor__n_estimators=50;, score=0.878 total time=   0.1s
[CV 10/10] END regressor__max_depth=None, regressor__max_features=sqrt, regressor__max_samples=0.25, regressor__n_estimators=50;, score=0.873 total time=   0.1s
[CV 1/10] END regressor__max_depth=None, regressor__max_features=sqrt, regressor__max_samples=0.25, regressor__n_estimators=100;, score=0.897 total time=   0.3s
[CV 2/10] END regressor__max_depth=None, regressor__max_features=sqrt, regressor__max_samples=0.25, regressor__n_estimators=100;, score=0.913 total time=   0.2s
[CV 3/10] END regressor__max_depth=None, regressor__max_features=sqrt, regressor__max_samples=0.25, regressor__n_estimators=100;, score=0.896 total time=   0.2s
[CV 4/10] END regressor__max_depth=None, regressor__max_features=sqrt, regressor__max_samples=0.25, regressor__n_estimators=100;, score=0.874 total time=   0.2s
[CV 5/10] END regressor__max_depth=None, regressor__max_features=sqrt, regressor__max_samples=0.25, regressor__n_estimators=100;, score=0.883 total time=   0.2s
[CV 6/10] END regressor__max_depth=None, regressor__max_features=sqrt, regressor__max_samples=0.25, regressor__n_estimators=100;, score=0.877 total time=   0.2s
[CV 9/10] END regressor__max_depth=None, regressor__max_features=sqrt, regressor__max_samples=0.5, regressor__n_estimators=50;, score=0.883 total time=   0.2s
[CV 10/10] END regressor__max_depth=None, regressor__max_features=sqrt, regressor__max_samples=0.5, regressor__n_estimators=50;, score=0.883 total time=   0.2s
[CV 1/10] END regressor__max_depth=None, regressor__max_features=sqrt, regressor__max_samples=0.5, regressor__n_estimators=100;, score=0.908 total time=   0.4s
[CV 2/10] END regressor__max_depth=None, regressor__max_features=sqrt, regressor__max_samples=0.5, regressor__n_estimators=100;, score=0.920 total time=   0.3s
[CV 3/10] END regressor__max_depth=None, regressor__max_features=sqrt, regressor__max_samples=0.5, regressor__n_estimators=100;, score=0.908 total time=   0.3s
[CV 4/10] END regressor__max_depth=None, regressor__max_features=sqrt, regressor__max_samples=0.5, regressor__n_estimators=100;, score=0.884 total time=   0.3s
[CV 5/10] END regressor__max_depth=None, regressor__max_features=sqrt, regressor__max_samples=0.5, regressor__n_estimators=100;, score=0.898 total time=   0.4s
[CV 6/10] END regressor__max_depth=None, regressor__max_features=sqrt, regressor__max_samples=0.5, regressor__n_estimators=100;, score=0.888 total time=   0.5s
[CV 1/10] END regressor__max_depth=10, regressor__max_features=auto, regressor__max_samples=0.1, regressor__n_estimators=50;, score=nan total time=   0.0s
[CV 2/10] END regressor__max_depth=10, regressor__max_features=auto, regressor__max_samples=0.1, regressor__n_estimators=50;, score=nan total time=   0.0s
[CV 3/10] END regressor__max_depth=10, regressor__max_features=auto, regressor__max_samples=0.1, regressor__n_estimators=50;, score=nan total time=   0.0s
[CV 4/10] END regressor__max_depth=10, regressor__max_features=auto, regressor__max_samples=0.1, regressor__n_estimators=50;, score=nan total time=   0.0s
[CV 5/10] END regressor__max_depth=10, regressor__max_features=auto, regressor__max_samples=0.1, regressor__n_estimators=50;, score=nan total time=   0.0s
[CV 6/10] END regressor__max_depth=10, regressor__max_features=auto, regressor__max_samples=0.1, regressor__n_estimators=50;, score=nan total time=   0.0s
[CV 7/10] END regressor__max_depth=10, regressor__max_features=auto, regressor__max_samples=0.1, regressor__n_estimators=50;, score=nan total time=   0.0s
[CV 8/10] END regressor__max_depth=10, regressor__max_features=auto, regressor__max_samples=0.1, regressor__n_estimators=50;, score=nan total time=   0.0s
[CV 9/10] END regressor__max_depth=10, regressor__max_features=auto, regressor__max_samples=0.1, regressor__n_estimators=50;, score=nan total time=   0.0s
[CV 10/10] END regressor__max_depth=10, regressor__max_features=auto, regressor__max_samples=0.1, regressor__n_estimators=50;, score=nan total time=   0.0s
[CV 1/10] END regressor__max_depth=10, regressor__max_features=auto, regressor__max_samples=0.1, regressor__n_estimators=100;, score=nan total time=   0.0s
[CV 2/10] END regressor__max_depth=10, regressor__max_features=auto, regressor__max_samples=0.1, regressor__n_estimators=100;, score=nan total time=   0.0s
[CV 3/10] END regressor__max_depth=10, regressor__max_features=auto, regressor__max_samples=0.1, regressor__n_estimators=100;, score=nan total time=   0.0s
[CV 4/10] END regressor__max_depth=10, regressor__max_features=auto, regressor__max_samples=0.1, regressor__n_estimators=100;, score=nan total time=   0.0s
[CV 5/10] END regressor__max_depth=10, regressor__max_features=auto, regressor__max_samples=0.1, regressor__n_estimators=100;, score=nan total time=   0.0s
[CV 6/10] END regressor__max_depth=10, regressor__max_features=auto, regressor__max_samples=0.1, regressor__n_estimators=100;, score=nan total time=   0.0s
[CV 7/10] END regressor__max_depth=10, regressor__max_features=auto, regressor__max_samples=0.1, regressor__n_estimators=100;, score=nan total time=   0.0s
[CV 8/10] END regressor__max_depth=10, regressor__max_features=auto, regressor__max_samples=0.1, regressor__n_estimators=100;, score=nan total time=   0.0s
[CV 9/10] END regressor__max_depth=10, regressor__max_features=auto, regressor__max_samples=0.1, regressor__n_estimators=100;, score=nan total time=   0.0s
[CV 10/10] END regressor__max_depth=10, regressor__max_features=auto, regressor__max_samples=0.1, regressor__n_estimators=100;, score=nan total time=   0.0s
[CV 1/10] END regressor__max_depth=10, regressor__max_features=auto, regressor__max_samples=0.1, regressor__n_estimators=200;, score=nan total time=   0.0s
[CV 2/10] END regressor__max_depth=10, regressor__max_features=auto, regressor__max_samples=0.1, regressor__n_estimators=200;, score=nan total time=   0.0s
[CV 3/10] END regressor__max_depth=10, regressor__max_features=auto, regressor__max_samples=0.1, regressor__n_estimators=200;, score=nan total time=   0.0s
[CV 4/10] END regressor__max_depth=10, regressor__max_features=auto, regressor__max_samples=0.1, regressor__n_estimators=200;, score=nan total time=   0.0s
[CV 5/10] END regressor__max_depth=10, regressor__max_features=auto, regressor__max_samples=0.1, regressor__n_estimators=200;, score=nan total time=   0.0s
[CV 6/10] END regressor__max_depth=10, regressor__max_features=auto, regressor__max_samples=0.1, regressor__n_estimators=200;, score=nan total time=   0.0s
[CV 7/10] END regressor__max_depth=10, regressor__max_features=auto, regressor__max_samples=0.1, regressor__n_estimators=200;, score=nan total time=   0.0s
[CV 8/10] END regressor__max_depth=10, regressor__max_features=auto, regressor__max_samples=0.1, regressor__n_estimators=200;, score=nan total time=   0.0s
[CV 9/10] END regressor__max_depth=10, regressor__max_features=auto, regressor__max_samples=0.1, regressor__n_estimators=200;, score=nan total time=   0.0s
[CV 10/10] END regressor__max_depth=10, regressor__max_features=auto, regressor__max_samples=0.1, regressor__n_estimators=200;, score=nan total time=   0.0s
[CV 1/10] END regressor__max_depth=10, regressor__max_features=auto, regressor__max_samples=0.1, regressor__n_estimators=300;, score=nan total time=   0.0s
[CV 2/10] END regressor__max_depth=10, regressor__max_features=auto, regressor__max_samples=0.1, regressor__n_estimators=300;, score=nan total time=   0.0s
[CV 3/10] END regressor__max_depth=10, regressor__max_features=auto, regressor__max_samples=0.1, regressor__n_estimators=300;, score=nan total time=   0.0s
[CV 4/10] END regressor__max_depth=10, regressor__max_features=auto, regressor__max_samples=0.1, regressor__n_estimators=300;, score=nan total time=   0.0s
[CV 5/10] END regressor__max_depth=10, regressor__max_features=auto, regressor__max_samples=0.1, regressor__n_estimators=300;, score=nan total time=   0.0s
[CV 6/10] END regressor__max_depth=10, regressor__max_features=auto, regressor__max_samples=0.1, regressor__n_estimators=300;, score=nan total time=   0.0s
[CV 7/10] END regressor__max_depth=10, regressor__max_features=auto, regressor__max_samples=0.1, regressor__n_estimators=300;, score=nan total time=   0.0s
[CV 8/10] END regressor__max_depth=10, regressor__max_features=auto, regressor__max_samples=0.1, regressor__n_estimators=300;, score=nan total time=   0.0s
[CV 9/10] END regressor__max_depth=10, regressor__max_features=auto, regressor__max_samples=0.1, regressor__n_estimators=300;, score=nan total time=   0.0s
[CV 10/10] END regressor__max_depth=10, regressor__max_features=auto, regressor__max_samples=0.1, regressor__n_estimators=300;, score=nan total time=   0.0s
[CV 1/10] END regressor__max_depth=10, regressor__max_features=auto, regressor__max_samples=0.25, regressor__n_estimators=50;, score=nan total time=   0.0s
[CV 2/10] END regressor__max_depth=10, regressor__max_features=auto, regressor__max_samples=0.25, regressor__n_estimators=50;, score=nan total time=   0.0s
[CV 3/10] END regressor__max_depth=10, regressor__max_features=auto, regressor__max_samples=0.25, regressor__n_estimators=50;, score=nan total time=   0.0s
[CV 4/10] END regressor__max_depth=10, regressor__max_features=auto, regressor__max_samples=0.25, regressor__n_estimators=50;, score=nan total time=   0.0s
[CV 5/10] END regressor__max_depth=10, regressor__max_features=auto, regressor__max_samples=0.25, regressor__n_estimators=50;, score=nan total time=   0.0s
[CV 6/10] END regressor__max_depth=10, regressor__max_features=auto, regressor__max_samples=0.25, regressor__n_estimators=50;, score=nan total time=   0.0s
[CV 7/10] END regressor__max_depth=10, regressor__max_features=auto, regressor__max_samples=0.25, regressor__n_estimators=50;, score=nan total time=   0.0s
[CV 8/10] END regressor__max_depth=10, regressor__max_features=auto, regressor__max_samples=0.25, regressor__n_estimators=50;, score=nan total time=   0.0s
[CV 5/10] END regressor__max_depth=10, regressor__max_features=auto, regressor__max_samples=0.25, regressor__n_estimators=200;, score=nan total time=   0.0s
[CV 6/10] END regressor__max_depth=10, regressor__max_features=auto, regressor__max_samples=0.25, regressor__n_estimators=200;, score=nan total time=   0.0s
[CV 7/10] END regressor__max_depth=10, regressor__max_features=auto, regressor__max_samples=0.25, regressor__n_estimators=200;, score=nan total time=   0.0s
[CV 8/10] END regressor__max_depth=10, regressor__max_features=auto, regressor__max_samples=0.25, regressor__n_estimators=200;, score=nan total time=   0.0s
[CV 9/10] END regressor__max_depth=10, regressor__max_features=auto, regressor__max_samples=0.25, regressor__n_estimators=200;, score=nan total time=   0.0s
[CV 10/10] END regressor__max_depth=10, regressor__max_features=auto, regressor__max_samples=0.25, regressor__n_estimators=200;, score=nan total time=   0.0s
[CV 1/10] END regressor__max_depth=10, regressor__max_features=auto, regressor__max_samples=0.25, regressor__n_estimators=300;, score=nan total time=   0.0s
[CV 2/10] END regressor__max_depth=10, regressor__max_features=auto, regressor__max_samples=0.25, regressor__n_estimators=300;, score=nan total time=   0.0s
[CV 3/10] END regressor__max_depth=10, regressor__max_features=auto, regressor__max_samples=0.25, regressor__n_estimators=300;, score=nan total time=   0.0s
[CV 4/10] END regressor__max_depth=10, regressor__max_features=auto, regressor__max_samples=0.25, regressor__n_estimators=300;, score=nan total time=   0.0s
[CV 5/10] END regressor__max_depth=10, regressor__max_features=auto, regressor__max_samples=0.25, regressor__n_estimators=300;, score=nan total time=   0.0s
[CV 6/10] END regressor__max_depth=10, regressor__max_features=auto, regressor__max_samples=0.25, regressor__n_estimators=300;, score=nan total time=   0.0s
[CV 7/10] END regressor__max_depth=10, regressor__max_features=auto, regressor__max_samples=0.25, regressor__n_estimators=300;, score=nan total time=   0.0s
[CV 8/10] END regressor__max_depth=10, regressor__max_features=auto, regressor__max_samples=0.25, regressor__n_estimators=300;, score=nan total time=   0.0s[CV 6/10] END regressor__max_depth=None, regressor__max_features=auto, regressor__max_samples=0.1, regressor__n_estimators=50;, score=nan total time=   0.0s
[CV 1/10] END regressor__max_depth=None, regressor__max_features=auto, regressor__max_samples=0.1, regressor__n_estimators=100;, score=nan total time=   0.0s
[CV 3/10] END regressor__max_depth=None, regressor__max_features=auto, regressor__max_samples=0.1, regressor__n_estimators=200;, score=nan total time=   0.0s
[CV 1/10] END regressor__max_depth=None, regressor__max_features=auto, regressor__max_samples=0.1, regressor__n_estimators=300;, score=nan total time=   0.0s
[CV 8/10] END regressor__max_depth=None, regressor__max_features=auto, regressor__max_samples=0.1, regressor__n_estimators=300;, score=nan total time=   0.0s
[CV 5/10] END regressor__max_depth=None, regressor__max_features=auto, regressor__max_samples=0.25, regressor__n_estimators=50;, score=nan total time=   0.0s
[CV 9/10] END regressor__max_depth=None, regressor__max_features=auto, regressor__max_samples=0.25, regressor__n_estimators=50;, score=nan total time=   0.0s
[CV 10/10] END regressor__max_depth=None, regressor__max_features=auto, regressor__max_samples=0.25, regressor__n_estimators=50;, score=nan total time=   0.0s
[CV 7/10] END regressor__max_depth=None, regressor__max_features=auto, regressor__max_samples=0.25, regressor__n_estimators=200;, score=nan total time=   0.0s
[CV 8/10] END regressor__max_depth=None, regressor__max_features=auto, regressor__max_samples=0.25, regressor__n_estimators=200;, score=nan total time=   0.0s
[CV 1/10] END regressor__max_depth=None, regressor__max_features=auto, regressor__max_samples=0.5, regressor__n_estimators=50;, score=nan total time=   0.0s
[CV 2/10] END regressor__max_depth=None, regressor__max_features=auto, regressor__max_samples=0.5, regressor__n_estimators=50;, score=nan total time=   0.0s
[CV 3/10] END regressor__max_depth=None, regressor__max_features=auto, regressor__max_samples=0.5, regressor__n_estimators=50;, score=nan total time=   0.0s
[CV 4/10] END regressor__max_depth=None, regressor__max_features=auto, regressor__max_samples=0.5, regressor__n_estimators=50;, score=nan total time=   0.0s
[CV 7/10] END regressor__max_depth=None, regressor__max_features=auto, regressor__max_samples=0.5, regressor__n_estimators=300;, score=nan total time=   0.0s
[CV 8/10] END regressor__max_depth=None, regressor__max_features=auto, regressor__max_samples=0.5, regressor__n_estimators=300;, score=nan total time=   0.0s
[CV 9/10] END regressor__max_depth=None, regressor__max_features=auto, regressor__max_samples=0.5, regressor__n_estimators=300;, score=nan total time=   0.0s
[CV 10/10] END regressor__max_depth=None, regressor__max_features=auto, regressor__max_samples=0.5, regressor__n_estimators=300;, score=nan total time=   0.0s
[CV 1/10] END regressor__max_depth=None, regressor__max_features=sqrt, regressor__max_samples=0.1, regressor__n_estimators=50;, score=0.887 total time=   0.1s
[CV 2/10] END regressor__max_depth=None, regressor__max_features=sqrt, regressor__max_samples=0.1, regressor__n_estimators=50;, score=0.895 total time=   0.1s
[CV 3/10] END regressor__max_depth=None, regressor__max_features=sqrt, regressor__max_samples=0.1, regressor__n_estimators=50;, score=0.875 total time=   0.1s

/opt/anaconda3/envs/py311_clean/lib/python3.11/site-packages/sklearn/model_selection/_validation.py:490: FitFailedWarning:
640 fits failed out of a total of 1280.
The score on these train-test partitions for these parameters will be set to nan.
If these failures are not expected, you can try to debug them by setting error_score='raise'.

Below are more details about the failures:
--------------------------------------------------------------------------------
389 fits failed with the following error:
Traceback (most recent call last):
  File "/opt/anaconda3/envs/py311_clean/lib/python3.11/site-packages/sklearn/model_selection/_validation.py", line 833, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
  File "/opt/anaconda3/envs/py311_clean/lib/python3.11/site-packages/sklearn/base.py", line 1336, in wrapper
    return fit_method(estimator, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/envs/py311_clean/lib/python3.11/site-packages/sklearn/pipeline.py", line 621, in fit
    self._final_estimator.fit(Xt, y, **last_step_params["fit"])
  File "/opt/anaconda3/envs/py311_clean/lib/python3.11/site-packages/sklearn/base.py", line 1329, in wrapper
    estimator._validate_params()
  File "/opt/anaconda3/envs/py311_clean/lib/python3.11/site-packages/sklearn/base.py", line 492, in _validate_params
    validate_parameter_constraints(
  File "/opt/anaconda3/envs/py311_clean/lib/python3.11/site-packages/sklearn/utils/_param_validation.py", line 98, in validate_parameter_constraints
    raise InvalidParameterError(
sklearn.utils._param_validation.InvalidParameterError: The 'max_features' parameter of RandomForestRegressor must be an int in the range [1, inf), a float in the range (0.0, 1.0], a str among {'log2', 'sqrt'} or None. Got 'auto' instead.

--------------------------------------------------------------------------------
251 fits failed with the following error:
Traceback (most recent call last):
  File "/opt/anaconda3/envs/py311_clean/lib/python3.11/site-packages/sklearn/model_selection/_validation.py", line 833, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
  File "/opt/anaconda3/envs/py311_clean/lib/python3.11/site-packages/sklearn/base.py", line 1336, in wrapper
    return fit_method(estimator, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/envs/py311_clean/lib/python3.11/site-packages/sklearn/pipeline.py", line 621, in fit
    self._final_estimator.fit(Xt, y, **last_step_params["fit"])
  File "/opt/anaconda3/envs/py311_clean/lib/python3.11/site-packages/sklearn/base.py", line 1329, in wrapper
    estimator._validate_params()
  File "/opt/anaconda3/envs/py311_clean/lib/python3.11/site-packages/sklearn/base.py", line 492, in _validate_params
    validate_parameter_constraints(
  File "/opt/anaconda3/envs/py311_clean/lib/python3.11/site-packages/sklearn/utils/_param_validation.py", line 98, in validate_parameter_constraints
    raise InvalidParameterError(
sklearn.utils._param_validation.InvalidParameterError: The 'max_features' parameter of RandomForestRegressor must be an int in the range [1, inf), a float in the range (0.0, 1.0], a str among {'sqrt', 'log2'} or None. Got 'auto' instead.

  warnings.warn(some_fits_failed_message, FitFailedWarning)
/opt/anaconda3/envs/py311_clean/lib/python3.11/site-packages/sklearn/model_selection/_search.py:1137: UserWarning: One or more of the test scores are non-finite: [       nan        nan        nan        nan        nan        nan
        nan        nan        nan        nan        nan        nan
        nan        nan        nan        nan 0.87011181 0.87168496
 0.87253932 0.87310157 0.88566662 0.88577871 0.8881483  0.88874538
 0.89660608 0.89606754 0.89696543 0.8970823  0.8995997  0.90183595
 0.90195768 0.90202815        nan        nan        nan        nan
        nan        nan        nan        nan        nan        nan
        nan        nan        nan        nan        nan        nan
 0.86551138 0.86809376 0.87166287 0.87095258 0.88210122 0.88256538
 0.88379843 0.88479644 0.88869844 0.88817537 0.88957979 0.89080082
 0.8919269  0.89265604 0.89369274 0.89339705        nan        nan
        nan        nan        nan        nan        nan        nan
        nan        nan        nan        nan        nan        nan
        nan        nan 0.86681933 0.87076468 0.87296129 0.87277811
 0.88415592 0.88613482 0.88780354 0.88790927 0.89364242 0.89543939
 0.89666235 0.89640477 0.90002077 0.90118892 0.90284233 0.90222874
        nan        nan        nan        nan        nan        nan
        nan        nan        nan        nan        nan        nan
        nan        nan        nan        nan 0.86994115 0.87176438
 0.87157853 0.87339409 0.88588503 0.88765207 0.88745602 0.88750117
 0.89245644 0.89604865 0.89571412 0.89653493 0.90079594 0.90141543
 0.90196311 0.90181171]
  warnings.warn(

GridSearchCV(cv=KFold(n_splits=10, random_state=42, shuffle=True),
             estimator=Pipeline(steps=[('preprocessor',
                                        ColumnTransformer(remainder='passthrough',
                                                          transformers=[('num',
                                                                         StandardScaler(),
                                                                         ['bedRoom',
                                                                          'bathroom',
                                                                          'built_up_area',
                                                                          'servant '
                                                                          'room',
                                                                          'store '
                                                                          'room']),
                                                                        ('cat',
                                                                         OrdinalEncoder(),
                                                                         ['property_type',
                                                                          'sector',
                                                                          'balcony',
                                                                          'agePossession',
                                                                          'furnishing_type',...
                                                                         OneHotEncoder(drop='first',
                                                                                       sparse_output=False),
                                                                         ['agePossession']),
                                                                        ('target_enc',
                                                                         TargetEncoder(),
                                                                         ['sector'])])),
                                       ('regressor', RandomForestRegressor())]),
             n_jobs=-1,
             param_grid={'regressor__max_depth': [None, 10, 20, 30],
                         'regressor__max_features': ['auto', 'sqrt'],
                         'regressor__max_samples': [0.1, 0.25, 0.5, 1.0],
                         'regressor__n_estimators': [50, 100, 200, 300]},
             scoring='r2', verbose=4)

In [134]:
final_pipe = search.best_estimator_

In [136]:
search.best_params_

{'regressor__max_depth': 20,
 'regressor__max_features': 'sqrt',
 'regressor__max_samples': 1.0,
 'regressor__n_estimators': 200}

In [138]:
search.best_score_

np.float64(0.9028423328064783)

In [142]:
final_pipe.fit(X,y_transformed)

Pipeline(steps=[('preprocessor',
                 ColumnTransformer(remainder='passthrough',
                                   transformers=[('num', StandardScaler(),
                                                  ['bedRoom', 'bathroom',
                                                   'built_up_area',
                                                   'servant room',
                                                   'store room']),
                                                 ('cat', OrdinalEncoder(),
                                                  ['property_type', 'sector',
                                                   'balcony', 'agePossession',
                                                   'furnishing_type',
                                                   'luxury_category',
                                                   'floor_category']),
                                                 ('cat1',
                                                  OneHotEncoder(drop='first',
                                                                sparse_output=False),
                                                  ['agePossession']),
                                                 ('target_enc', TargetEncoder(),
                                                  ['sector'])])),
                ('regressor',
                 RandomForestRegressor(max_depth=20, max_features='sqrt',
                                       max_samples=1.0, n_estimators=200))])

# Xgboost With Hyper parametertunning

In [19]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    X, y_transformed, test_size=0.2, random_state=42
)

In [21]:
# Before fitting we should split bcz data leakage will happen

In [23]:
from xgboost import XGBRegressor
from sklearn.pipeline import Pipeline
from sklearn.compose import ColumnTransformer
from sklearn.model_selection import GridSearchCV, KFold
from sklearn.preprocessing import StandardScaler, OneHotEncoder, OrdinalEncoder
import category_encoders as ce

# -------------------------------
# Columns
# -------------------------------
num_cols = ['bedRoom', 'bathroom', 'built_up_area', 'servant room', 'store room']

cat_cols = [
    'property_type', 'balcony', 'furnishing_type',
    'luxury_category', 'floor_category'
]

# -------------------------------
# Preprocessor
# -------------------------------
preprocessor = ColumnTransformer(
    transformers=[
        ('num', StandardScaler(), num_cols),
        ('ord', OrdinalEncoder(), cat_cols),
        ('ohe', OneHotEncoder(drop='first', sparse_output=False), ['agePossession']),
        ('target', ce.TargetEncoder(), ['sector'])
    ],
    remainder='passthrough'
)

# -------------------------------
# Pipeline
# -------------------------------
pipeline = Pipeline([
    ('preprocessor', preprocessor),
    ('regressor', XGBRegressor(
        objective='reg:squarederror',
        random_state=42,
        n_jobs=-1
    ))
])

# -------------------------------
# Hyperparameter Grid
# -------------------------------
param_grid = {
    'regressor__n_estimators': [100, 200, 300],
    'regressor__max_depth': [3, 5, 7],
    'regressor__learning_rate': [0.05, 0.1],
    'regressor__subsample': [0.7, 0.9, 1.0],
    'regressor__colsample_bytree': [0.7, 0.9, 1.0]
}

# -------------------------------
# Cross Validation
# -------------------------------
kfold = KFold(n_splits=10, shuffle=True, random_state=42)

# -------------------------------
# Grid Search
# -------------------------------
search = GridSearchCV(
    estimator=pipeline,
    param_grid=param_grid,
    cv=kfold,
    scoring='r2',
    n_jobs=-1,
    verbose=4
)

In [25]:
# -------------------------------
# Fit
# -------------------------------
search.fit(X_train, y_train)

Fitting 10 folds for each of 162 candidates, totalling 1620 fits
[CV 6/10] END regressor__colsample_bytree=0.7, regressor__learning_rate=0.05, regressor__max_depth=3, regressor__n_estimators=100, regressor__subsample=0.7;, score=0.893 total time=   0.1s
[CV 3/10] END regressor__colsample_bytree=0.7, regressor__learning_rate=0.05, regressor__max_depth=3, regressor__n_estimators=100, regressor__subsample=0.9;, score=0.869 total time=   0.0s
[CV 10/10] END regressor__colsample_bytree=0.7, regressor__learning_rate=0.05, regressor__max_depth=3, regressor__n_estimators=100, regressor__subsample=0.9;, score=0.852 total time=   0.0s
[CV 6/10] END regressor__colsample_bytree=0.7, regressor__learning_rate=0.05, regressor__max_depth=3, regressor__n_estimators=100, regressor__subsample=1.0;, score=0.892 total time=   0.1s
[CV 4/10] END regressor__colsample_bytree=0.7, regressor__learning_rate=0.05, regressor__max_depth=3, regressor__n_estimators=200, regressor__subsample=0.7;, score=0.903 total time=   0.1s
[CV 2/10] END regressor__colsample_bytree=0.7, regressor__learning_rate=0.05, regressor__max_depth=3, regressor__n_estimators=200, regressor__subsample=0.9;, score=0.874 total time=   0.1s
[CV 9/10] END regressor__colsample_bytree=0.7, regressor__learning_rate=0.05, regressor__max_depth=3, regressor__n_estimators=200, regressor__subsample=0.9;, score=0.911 total time=   0.1s
[CV 10/10] END regressor__colsample_bytree=0.7, regressor__learning_rate=0.05, regressor__max_depth=3, regressor__n_estimators=200, regressor__subsample=0.9;, score=0.859 total time=   0.1s
[CV 5/10] END regressor__colsample_bytree=0.7, regressor__learning_rate=0.05, regressor__max_depth=3, regressor__n_estimators=300, regressor__subsample=0.7;, score=0.877 total time=   0.1s
[CV 6/10] END regressor__colsample_bytree=0.7, regressor__learning_rate=0.05, regressor__max_depth=3, regressor__n_estimators=300, regressor__subsample=0.7;, score=0.902 total time=   0.1s
[CV 1/10] END regressor__colsample_bytree=0.7, regressor__learning_rate=0.05, regressor__max_depth=3, regressor__n_estimators=300, regressor__subsample=1.0;, score=0.889 total time=   0.1s
[CV 2/10] END regressor__colsample_bytree=0.7, regressor__learning_rate=0.05, regressor__max_depth=3, regressor__n_estimators=300, regressor__subsample=1.0;, score=0.873 total time=   0.1s
[CV 7/10] END regressor__colsample_bytree=0.7, regressor__learning_rate=0.05, regressor__max_depth=5, regressor__n_estimators=100, regressor__subsample=0.7;, score=0.860 total time=   0.1s
[CV 8/10] END regressor__colsample_bytree=0.7, regressor__learning_rate=0.05, regressor__max_depth=5, regressor__n_estimators=100, regressor__subsample=0.7;, score=0.876 total time=   0.1s
[CV 3/10] END regressor__colsample_bytree=0.7, regressor__learning_rate=0.05, regressor__max_depth=5, regressor__n_estimators=100, regressor__subsample=1.0;, score=0.886 total time=   0.1s
[CV 4/10] END regressor__colsample_bytree=0.7, regressor__learning_rate=0.05, regressor__max_depth=5, regressor__n_estimators=100, regressor__subsample=1.0;, score=0.913 total time=   0.1s
[CV 9/10] END regressor__colsample_bytree=0.7, regressor__learning_rate=0.05, regressor__max_depth=5, regressor__n_estimators=200, regressor__subsample=0.7;, score=0.920 total time=   0.1s
[CV 10/10] END regressor__colsample_bytree=0.7, regressor__learning_rate=0.05, regressor__max_depth=5, regressor__n_estimators=200, regressor__subsample=0.7;, score=0.870 total time=   0.1s
[CV 7/10] END regressor__colsample_bytree=0.7, regressor__learning_rate=0.05, regressor__max_depth=5, regressor__n_estimators=200, regressor__subsample=1.0;, score=0.856 total time=   0.1s
[CV 8/10] END regressor__colsample_bytree=0.7, regressor__learning_rate=0.05, regressor__max_depth=5, regressor__n_estimators=200, regressor__subsample=1.0;, score=0.884 total time=   0.1s
[CV 3/10] END regressor__colsample_bytree=0.7, regressor__learning_rate=0.05, regressor__max_depth=5, regressor__n_estimators=300, regressor__subsample=0.9;, score=0.897 total time=   0.2s
[CV 4/10] END regressor__colsample_bytree=0.7, regressor__learning_rate=0.05, regressor__max_depth=5, regressor__n_estimators=300, regressor__subsample=0.9;, score=0.923 total time=   0.2s
[CV 9/10] END regressor__colsample_bytree=0.7, regressor__learning_rate=0.05, regressor__max_depth=5, regressor__n_estimators=300, regressor__subsample=1.0;, score=0.920 total time=   0.1s
[CV 10/10] END regressor__colsample_bytree=0.7, regressor__learning_rate=0.05, regressor__max_depth=5, regressor__n_estimators=300, regressor__subsample=1.0;, score=0.871 total time=   0.1s
[CV 3/10] END regressor__colsample_bytree=0.7, regressor__learning_rate=0.05, regressor__max_depth=7, regressor__n_estimators=100, regressor__subsample=0.9;, score=0.894 total time=   0.1s
[CV 4/10] END regressor__colsample_bytree=0.7, regressor__learning_rate=0.05, regressor__max_depth=7, regressor__n_estimators=100, regressor__subsample=0.9;, score=0.920 total time=   0.1s
[CV 9/10] END regressor__colsample_bytree=0.7, regressor__learning_rate=0.05, regressor__max_depth=7, regressor__n_estimators=100, regressor__subsample=1.0;, score=0.913 total time=   0.1s
[CV 10/10] END regressor__colsample_bytree=0.7, regressor__learning_rate=0.05, regressor__max_depth=7, regressor__n_estimators=100, regressor__subsample=1.0;, score=0.864 total time=   0.1s
[CV 5/10] END regressor__colsample_bytree=0.7, regressor__learning_rate=0.05, regressor__max_depth=7, regressor__n_estimators=200, regressor__subsample=0.9;, score=0.893 total time=   0.2s
[CV 6/10] END regressor__colsample_bytree=0.7, regressor__learning_rate=0.05, regressor__max_depth=7, regressor__n_estimators=200, regressor__subsample=0.9;, score=0.918 total time=   0.2s
[CV 1/10] END regressor__colsample_bytree=0.7, regressor__learning_rate=0.05, regressor__max_depth=7, regressor__n_estimators=300, regressor__subsample=0.7;, score=0.903 total time=   0.3s
[CV 2/10] END regressor__colsample_bytree=0.7, regressor__learning_rate=0.05, regressor__max_depth=7, regressor__n_estimators=300, regressor__subsample=0.7;, score=0.899 total time=   0.3s
[CV 7/10] END regressor__colsample_bytree=0.7, regressor__learning_rate=0.05, regressor__max_depth=7, regressor__n_estimators=300, regressor__subsample=0.9;, score=0.859 total time=   0.3s
[CV 8/10] END regressor__colsample_bytree=0.7, regressor__learning_rate=0.05, regressor__max_depth=7, regressor__n_estimators=300, regressor__subsample=0.9;, score=0.892 total time=   0.3s
[CV 5/10] END regressor__colsample_bytree=0.7, regressor__learning_rate=0.1, regressor__max_depth=3, regressor__n_estimators=100, regressor__subsample=0.7;, score=0.878 total time=   0.1s
[CV 6/10] END regressor__colsample_bytree=0.7, regressor__learning_rate=0.1, regressor__max_depth=3, regressor__n_estimators=100, regressor__subsample=0.7;, score=0.896 total time=   0.1s
[CV 9/10] END regressor__colsample_bytree=0.7, regressor__learning_rate=0.1, regressor__max_depth=3, regressor__n_estimators=100, regressor__subsample=0.7;, score=0.913 total time=   0.1s
[CV 10/10] END regressor__colsample_bytree=0.7, regressor__learning_rate=0.1, regressor__max_depth=3, regressor__n_estimators=100, regressor__subsample=0.7;, score=0.857 total time=   0.1s
[CV 1/10] END regressor__colsample_bytree=0.7, regressor__learning_rate=0.1, regressor__max_depth=3, regressor__n_estimators=100, regressor__subsample=1.0;, score=0.890 total time=   0.1s
[CV 2/10] END regressor__colsample_bytree=0.7, regressor__learning_rate=0.1, regressor__max_depth=3, regressor__n_estimators=100, regressor__subsample=1.0;, score=0.872 total time=   0.1s
[CV 9/10] END regressor__colsample_bytree=0.7, regressor__learning_rate=0.1, regressor__max_depth=3, regressor__n_estimators=200, regressor__subsample=0.7;, score=0.918 total time=   0.1s
[CV 10/10] END regressor__colsample_bytree=0.7, regressor__learning_rate=0.1, regressor__max_depth=3, regressor__n_estimators=200, regressor__subsample=0.7;, score=0.865 total time=   0.1s
[CV 5/10] END regressor__colsample_bytree=0.7, regressor__learning_rate=0.1, regressor__max_depth=3, regressor__n_estimators=200, regressor__subsample=1.0;, score=0.879 total time=   0.1s
[CV 6/10] END regressor__colsample_bytree=0.7, regressor__learning_rate=0.1, regressor__max_depth=3, regressor__n_estimators=200, regressor__subsample=1.0;, score=0.901 total time=   0.1s[CV 4/10] END regressor__colsample_bytree=0.7, regressor__learning_rate=0.05, regressor__max_depth=3, regressor__n_estimators=100, regressor__subsample=0.7;, score=0.899 total time=   0.1s
[CV 9/10] END regressor__colsample_bytree=0.7, regressor__learning_rate=0.05, regressor__max_depth=3, regressor__n_estimators=100, regressor__subsample=0.7;, score=0.904 total time=   0.0s
[CV 10/10] END regressor__colsample_bytree=0.7, regressor__learning_rate=0.05, regressor__max_depth=3, regressor__n_estimators=100, regressor__subsample=0.7;, score=0.854 total time=   0.1s
[CV 7/10] END regressor__colsample_bytree=0.7, regressor__learning_rate=0.05, regressor__max_depth=3, regressor__n_estimators=100, regressor__subsample=0.9;, score=0.831 total time=   0.1s
[CV 5/10] END regressor__colsample_bytree=0.7, regressor__learning_rate=0.05, regressor__max_depth=3, regressor__n_estimators=100, regressor__subsample=1.0;, score=0.866 total time=   0.0s
[CV 3/10] END regressor__colsample_bytree=0.7, regressor__learning_rate=0.05, regressor__max_depth=3, regressor__n_estimators=200, regressor__subsample=0.7;, score=0.887 total time=   0.1s
[CV 10/10] END regressor__colsample_bytree=0.7, regressor__learning_rate=0.05, regressor__max_depth=3, regressor__n_estimators=200, regressor__subsample=0.7;, score=0.860 total time=   0.1s
[CV 8/10] END regressor__colsample_bytree=0.7, regressor__learning_rate=0.05, regressor__max_depth=3, regressor__n_estimators=200, regressor__subsample=0.9;, score=0.869 total time=   0.1s
[CV 3/10] END regressor__colsample_bytree=0.7, regressor__learning_rate=0.05, regressor__max_depth=3, regressor__n_estimators=300, regressor__subsample=0.7;, score=0.890 total time=   0.1s
[CV 4/10] END regressor__colsample_bytree=0.7, regressor__learning_rate=0.05, regressor__max_depth=3, regressor__n_estimators=300, regressor__subsample=0.7;, score=0.907 total time=   0.1s
[CV 7/10] END regressor__colsample_bytree=0.7, regressor__learning_rate=0.05, regressor__max_depth=3, regressor__n_estimators=300, regressor__subsample=0.9;, score=0.845 total time=   0.1s
[CV 8/10] END regressor__colsample_bytree=0.7, regressor__learning_rate=0.05, regressor__max_depth=3, regressor__n_estimators=300, regressor__subsample=0.9;, score=0.875 total time=   0.1s
[CV 3/10] END regressor__colsample_bytree=0.7, regressor__learning_rate=0.05, regressor__max_depth=5, regressor__n_estimators=100, regressor__subsample=0.7;, score=0.888 total time=   0.1s
[CV 4/10] END regressor__colsample_bytree=0.7, regressor__learning_rate=0.05, regressor__max_depth=5, regressor__n_estimators=100, regressor__subsample=0.7;, score=0.919 total time=   0.1s
[CV 9/10] END regressor__colsample_bytree=0.7, regressor__learning_rate=0.05, regressor__max_depth=5, regressor__n_estimators=100, regressor__subsample=0.9;, score=0.911 total time=   0.1s
[CV 10/10] END regressor__colsample_bytree=0.7, regressor__learning_rate=0.05, regressor__max_depth=5, regressor__n_estimators=100, regressor__subsample=0.9;, score=0.862 total time=   0.1s
[CV 3/10] END regressor__colsample_bytree=0.7, regressor__learning_rate=0.05, regressor__max_depth=5, regressor__n_estimators=200, regressor__subsample=0.7;, score=0.895 total time=   0.1s
[CV 4/10] END regressor__colsample_bytree=0.7, regressor__learning_rate=0.05, regressor__max_depth=5, regressor__n_estimators=200, regressor__subsample=0.7;, score=0.924 total time=   0.1s
[CV 1/10] END regressor__colsample_bytree=0.7, regressor__learning_rate=0.05, regressor__max_depth=5, regressor__n_estimators=200, regressor__subsample=1.0;, score=0.894 total time=   0.1s
[CV 2/10] END regressor__colsample_bytree=0.7, regressor__learning_rate=0.05, regressor__max_depth=5, regressor__n_estimators=200, regressor__subsample=1.0;, score=0.885 total time=   0.1s
[CV 7/10] END regressor__colsample_bytree=0.7, regressor__learning_rate=0.05, regressor__max_depth=5, regressor__n_estimators=300, regressor__subsample=0.7;, score=0.861 total time=   0.2s
[CV 8/10] END regressor__colsample_bytree=0.7, regressor__learning_rate=0.05, regressor__max_depth=5, regressor__n_estimators=300, regressor__subsample=0.7;, score=0.885 total time=   0.2s
[CV 3/10] END regressor__colsample_bytree=0.7, regressor__learning_rate=0.05, regressor__max_depth=5, regressor__n_estimators=300, regressor__subsample=1.0;, score=0.895 total time=   0.2s
[CV 4/10] END regressor__colsample_bytree=0.7, regressor__learning_rate=0.05, regressor__max_depth=5, regressor__n_estimators=300, regressor__subsample=1.0;, score=0.918 total time=   0.2s
[CV 9/10] END regressor__colsample_bytree=0.7, regressor__learning_rate=0.05, regressor__max_depth=7, regressor__n_estimators=100, regressor__subsample=0.7;, score=0.916 total time=   0.1s
[CV 10/10] END regressor__colsample_bytree=0.7, regressor__learning_rate=0.05, regressor__max_depth=7, regressor__n_estimators=100, regressor__subsample=0.7;, score=0.865 total time=   0.1s
[CV 5/10] END regressor__colsample_bytree=0.7, regressor__learning_rate=0.05, regressor__max_depth=7, regressor__n_estimators=100, regressor__subsample=1.0;, score=0.884 total time=   0.1s
[CV 6/10] END regressor__colsample_bytree=0.7, regressor__learning_rate=0.05, regressor__max_depth=7, regressor__n_estimators=100, regressor__subsample=1.0;, score=0.918 total time=   0.2s
[CV 1/10] END regressor__colsample_bytree=0.7, regressor__learning_rate=0.05, regressor__max_depth=7, regressor__n_estimators=200, regressor__subsample=0.9;, score=0.902 total time=   0.2s
[CV 2/10] END regressor__colsample_bytree=0.7, regressor__learning_rate=0.05, regressor__max_depth=7, regressor__n_estimators=200, regressor__subsample=0.9;, score=0.894 total time=   0.2s
[CV 7/10] END regressor__colsample_bytree=0.7, regressor__learning_rate=0.05, regressor__max_depth=7, regressor__n_estimators=200, regressor__subsample=1.0;, score=0.854 total time=   0.2s
[CV 8/10] END regressor__colsample_bytree=0.7, regressor__learning_rate=0.05, regressor__max_depth=7, regressor__n_estimators=200, regressor__subsample=1.0;, score=0.892 total time=   0.2s
[CV 3/10] END regressor__colsample_bytree=0.7, regressor__learning_rate=0.05, regressor__max_depth=7, regressor__n_estimators=300, regressor__subsample=0.9;, score=0.901 total time=   0.3s
[CV 4/10] END regressor__colsample_bytree=0.7, regressor__learning_rate=0.05, regressor__max_depth=7, regressor__n_estimators=300, regressor__subsample=0.9;, score=0.924 total time=   0.3s
[CV 1/10] END regressor__colsample_bytree=0.7, regressor__learning_rate=0.1, regressor__max_depth=3, regressor__n_estimators=100, regressor__subsample=0.7;, score=0.888 total time=   0.1s
[CV 2/10] END regressor__colsample_bytree=0.7, regressor__learning_rate=0.1, regressor__max_depth=3, regressor__n_estimators=100, regressor__subsample=0.7;, score=0.877 total time=   0.1s
[CV 3/10] END regressor__colsample_bytree=0.7, regressor__learning_rate=0.1, regressor__max_depth=3, regressor__n_estimators=100, regressor__subsample=0.7;, score=0.884 total time=   0.1s
[CV 4/10] END regressor__colsample_bytree=0.7, regressor__learning_rate=0.1, regressor__max_depth=3, regressor__n_estimators=100, regressor__subsample=0.7;, score=0.903 total time=   0.1s
[CV 7/10] END regressor__colsample_bytree=0.7, regressor__learning_rate=0.1, regressor__max_depth=3, regressor__n_estimators=100, regressor__subsample=0.7;, score=0.839 total time=   0.1s
[CV 8/10] END regressor__colsample_bytree=0.7, regressor__learning_rate=0.1, regressor__max_depth=3, regressor__n_estimators=100, regressor__subsample=0.7;, score=0.867 total time=   0.1s
[CV 9/10] END regressor__colsample_bytree=0.7, regressor__learning_rate=0.1, regressor__max_depth=3, regressor__n_estimators=100, regressor__subsample=0.9;, score=0.910 total time=   0.1s
[CV 10/10] END regressor__colsample_bytree=0.7, regressor__learning_rate=0.1, regressor__max_depth=3, regressor__n_estimators=100, regressor__subsample=0.9;, score=0.863 total time=   0.1s
[CV 5/10] END regressor__colsample_bytree=0.7, regressor__learning_rate=0.1, regressor__max_depth=3, regressor__n_estimators=200, regressor__subsample=0.7;, score=0.879 total time=   0.1s
[CV 6/10] END regressor__colsample_bytree=0.7, regressor__learning_rate=0.1, regressor__max_depth=3, regressor__n_estimators=200, regressor__subsample=0.7;, score=0.899 total time=   0.1s[CV 3/10] END regressor__colsample_bytree=0.7, regressor__learning_rate=0.05, regressor__max_depth=3, regressor__n_estimators=100, regressor__subsample=0.7;, score=0.873 total time=   0.1s
[CV 3/10] END regressor__colsample_bytree=0.7, regressor__learning_rate=0.05, regressor__max_depth=3, regressor__n_estimators=100, regressor__subsample=1.0;, score=0.867 total time=   0.0s
[CV 2/10] END regressor__colsample_bytree=0.7, regressor__learning_rate=0.05, regressor__max_depth=3, regressor__n_estimators=200, regressor__subsample=0.7;, score=0.873 total time=   0.1s
[CV 9/10] END regressor__colsample_bytree=0.7, regressor__learning_rate=0.05, regressor__max_depth=3, regressor__n_estimators=200, regressor__subsample=0.7;, score=0.911 total time=   0.1s
[CV 7/10] END regressor__colsample_bytree=0.7, regressor__learning_rate=0.05, regressor__max_depth=3, regressor__n_estimators=200, regressor__subsample=0.9;, score=0.839 total time=   0.1s
[CV 1/10] END regressor__colsample_bytree=0.7, regressor__learning_rate=0.05, regressor__max_depth=3, regressor__n_estimators=300, regressor__subsample=0.7;, score=0.891 total time=   0.1s
[CV 2/10] END regressor__colsample_bytree=0.7, regressor__learning_rate=0.05, regressor__max_depth=3, regressor__n_estimators=300, regressor__subsample=0.7;, score=0.876 total time=   0.1s
[CV 9/10] END regressor__colsample_bytree=0.7, regressor__learning_rate=0.05, regressor__max_depth=3, regressor__n_estimators=300, regressor__subsample=0.9;, score=0.915 total time=   0.1s
[CV 10/10] END regressor__colsample_bytree=0.7, regressor__learning_rate=0.05, regressor__max_depth=3, regressor__n_estimators=300, regressor__subsample=0.9;, score=0.861 total time=   0.1s
[CV 5/10] END regressor__colsample_bytree=0.7, regressor__learning_rate=0.05, regressor__max_depth=5, regressor__n_estimators=100, regressor__subsample=0.7;, score=0.885 total time=   0.1s
[CV 6/10] END regressor__colsample_bytree=0.7, regressor__learning_rate=0.05, regressor__max_depth=5, regressor__n_estimators=100, regressor__subsample=0.7;, score=0.909 total time=   0.1s
[CV 1/10] END regressor__colsample_bytree=0.7, regressor__learning_rate=0.05, regressor__max_depth=5, regressor__n_estimators=100, regressor__subsample=1.0;, score=0.890 total time=   0.1s
[CV 2/10] END regressor__colsample_bytree=0.7, regressor__learning_rate=0.05, regressor__max_depth=5, regressor__n_estimators=100, regressor__subsample=1.0;, score=0.885 total time=   0.1s
[CV 5/10] END regressor__colsample_bytree=0.7, regressor__learning_rate=0.05, regressor__max_depth=5, regressor__n_estimators=200, regressor__subsample=0.7;, score=0.888 total time=   0.1s
[CV 6/10] END regressor__colsample_bytree=0.7, regressor__learning_rate=0.05, regressor__max_depth=5, regressor__n_estimators=200, regressor__subsample=0.7;, score=0.913 total time=   0.1s
[CV 9/10] END regressor__colsample_bytree=0.7, regressor__learning_rate=0.05, regressor__max_depth=5, regressor__n_estimators=200, regressor__subsample=0.9;, score=0.920 total time=   0.1s
[CV 10/10] END regressor__colsample_bytree=0.7, regressor__learning_rate=0.05, regressor__max_depth=5, regressor__n_estimators=200, regressor__subsample=0.9;, score=0.867 total time=   0.1s

GridSearchCV(cv=KFold(n_splits=10, random_state=42, shuffle=True),
             estimator=Pipeline(steps=[('preprocessor',
                                        ColumnTransformer(remainder='passthrough',
                                                          transformers=[('num',
                                                                         StandardScaler(),
                                                                         ['bedRoom',
                                                                          'bathroom',
                                                                          'built_up_area',
                                                                          'servant '
                                                                          'room',
                                                                          'store '
                                                                          'room']),
                                                                        ('ord',
                                                                         OrdinalEncoder(),
                                                                         ['property_type',
                                                                          'balcony',
                                                                          'furnishing_type',
                                                                          'luxury_category',
                                                                          'floor_...
                                                     missing=nan,
                                                     monotone_constraints=None,
                                                     multi_strategy=None,
                                                     n_estimators=None,
                                                     n_jobs=-1,
                                                     num_parallel_tree=None, ...))]),
             n_jobs=-1,
             param_grid={'regressor__colsample_bytree': [0.7, 0.9, 1.0],
                         'regressor__learning_rate': [0.05, 0.1],
                         'regressor__max_depth': [3, 5, 7],
                         'regressor__n_estimators': [100, 200, 300],
                         'regressor__subsample': [0.7, 0.9, 1.0]},
             scoring='r2', verbose=4)

In [27]:
search.best_params_

{'regressor__colsample_bytree': 0.7,
 'regressor__learning_rate': 0.05,
 'regressor__max_depth': 7,
 'regressor__n_estimators': 300,
 'regressor__subsample': 0.7}

In [31]:
# Results
best_model = search.best_estimator_

y_pred = best_model.predict(X_test)

from sklearn.metrics import r2_score, mean_absolute_error
import numpy as np

print("Test R²:", r2_score(y_test, y_pred))
print("Test MAE:", mean_absolute_error(y_test, y_pred))
# -------------------------------

Test R²: 0.9168056185663107
Test MAE: 0.10821142292885332

In [33]:
print("Train R²:", best_model.score(X_train, y_train))
print("Test R²:", best_model.score(X_test, y_test))

Train R²: 0.9855962420667617
Test R²: 0.9168056185663107

In [35]:
# Test the model

In [37]:
best_model = search.best_estimator_

In [39]:
X_test.sample()

,property_type,sector,bedRoom,bathroom,balcony,agePossession,built_up_area,servant room,store room,furnishing_type,luxury_category,floor_category
897,house,sector 4,2.0,3.0,1,Moderately Old,675.0,0.0,0.0,unfurnished,Low,Low Floor

In [43]:
# Select the row (keep it as DataFrame, not Series)
single_row = X_test.loc[[102]]

pred_log = best_model.predict(single_row)

import numpy as np
pred_price = np.expm1(pred_log)

print("Predicted Price:", pred_price[0])

Predicted Price: 1.2398125

In [45]:
actual_price = np.expm1(y_test.loc[102])
print("Actual Price:", actual_price)

Actual Price: 0.8500000000000001

In [509]:
df.loc[[102]]

,property_type,sector,price,bedRoom,bathroom,balcony,agePossession,built_up_area,servant room,store room,furnishing_type,luxury_category,floor_category
102,flat,manesar,0.85,3.0,3.0,2,Moderately Old,2556.0,0.0,0.0,0.0,Low,Low Floor

### Exporting the model

* Xgboost model

In [511]:
preprocessor = ColumnTransformer(
    transformers=[
        ('num', StandardScaler(), num_cols),
        ('ord', OrdinalEncoder(), cat_cols),
        ('ohe', OneHotEncoder(drop='first', sparse_output=False), ['agePossession']),
        ('target', ce.TargetEncoder(), ['sector'])
    ],
    remainder='passthrough'
)

In [513]:
from sklearn.pipeline import Pipeline
from sklearn.ensemble import RandomForestRegressor

pipeline = Pipeline([
    ('preprocessor', preprocessor),
    ('regressor', XGBRegressor(
        objective='reg:squarederror',
        n_estimators=300,
        max_depth=7,
        learning_rate=0.05,
        subsample=0.7,
        colsample_bytree=0.7,
        random_state=42,
        n_jobs=-1
    ))
])

In [515]:
pipeline.fit(X,y_transformed)

Pipeline(steps=[('preprocessor',
                 ColumnTransformer(remainder='passthrough',
                                   transformers=[('num', StandardScaler(),
                                                  ['bedRoom', 'bathroom',
                                                   'built_up_area',
                                                   'servant room',
                                                   'store room']),
                                                 ('ord', OrdinalEncoder(),
                                                  ['property_type', 'balcony',
                                                   'furnishing_type',
                                                   'luxury_category',
                                                   'floor_category']),
                                                 ('ohe',
                                                  OneHotEncoder(drop='first',
                                                                sparse_output=False),
                                                  ['agePosses...
                              feature_types=None, feature_weights=None,
                              gamma=None, grow_policy=None,
                              importance_type=None,
                              interaction_constraints=None, learning_rate=0.05,
                              max_bin=None, max_cat_threshold=None,
                              max_cat_to_onehot=None, max_delta_step=None,
                              max_depth=7, max_leaves=None,
                              min_child_weight=None, missing=nan,
                              monotone_constraints=None, multi_strategy=None,
                              n_estimators=300, n_jobs=-1,
                              num_parallel_tree=None, ...))])

In [517]:
import pickle

with open('pipeline.pkl', 'wb') as file:
    pickle.dump(pipeline, file)

In [519]:
with open('df.pkl', 'wb') as file:
    pickle.dump(X, file)

In [521]:
X

,property_type,sector,bedRoom,bathroom,balcony,agePossession,built_up_area,servant room,store room,furnishing_type,luxury_category,floor_category
0,flat,sector 36,3.0,2.0,2,New Property,850.0,0.0,0.0,unfurnished,Low,Low Floor
1,flat,sector 89,2.0,2.0,2,New Property,1226.0,1.0,0.0,unfurnished,Low,Mid Floor
2,flat,sohna road,2.0,2.0,1,New Property,1000.0,0.0,0.0,unfurnished,Low,High Floor
3,flat,sector 92,3.0,4.0,3+,Relatively New,1615.0,1.0,0.0,semifurnished,High,Mid Floor
4,flat,sector 102,2.0,2.0,1,Relatively New,582.0,0.0,1.0,unfurnished,High,Mid Floor
...,...,...,...,...,...,...,...,...,...,...,...,...
3549,flat,sector 84,2.0,2.0,1,Relatively New,532.0,0.0,0.0,unfurnished,Medium,Mid Floor
3550,house,sector 109,5.0,5.0,3+,Relatively New,6228.0,1.0,1.0,unfurnished,High,Low Floor
3551,flat,sector 2,1.0,1.0,1,Moderately Old,665.0,0.0,0.0,semifurnished,Medium,Mid Floor
3552,house,sector 43,5.0,6.0,3,Moderately Old,5490.0,1.0,1.0,unfurnished,Medium,Mid Floor
3553,flat,sector 68,3.0,3.0,3+,Relatively New,1845.0,0.0,0.0,semifurnished,Medium,High Floor

### Trying out the predictions

In [523]:
X.columns

Index(['property_type', 'sector', 'bedRoom', 'bathroom', 'balcony',
       'agePossession', 'built_up_area', 'servant room', 'store room',
       'furnishing_type', 'luxury_category', 'floor_category'],
      dtype='object')

In [525]:
X.iloc[0].values

array(['flat', 'sector 36', np.float64(3.0), np.float64(2.0), '2',
       'New Property', np.float64(850.0), np.float64(0.0),
       np.float64(0.0), 'unfurnished', 'Low', 'Low Floor'], dtype=object)

In [565]:
data = [['house', 'sector 102', 4, 3, '3+', 'New Property', 2750, 0, 0, 'unfurnished', 'Low', 'Low Floor']]
columns = ['property_type', 'sector', 'bedRoom', 'bathroom', 'balcony',
       'agePossession', 'built_up_area', 'servant room', 'store room',
       'furnishing_type', 'luxury_category', 'floor_category']

# Convert to DataFrame
one_df = pd.DataFrame(data, columns=columns)

one_df

,property_type,sector,bedRoom,bathroom,balcony,agePossession,built_up_area,servant room,store room,furnishing_type,luxury_category,floor_category
0,house,sector 102,4,3,3+,New Property,2750,0,0,unfurnished,Low,Low Floor

In [569]:
np.expm1(pipeline.predict(one_df))

array([3.325391], dtype=float32)

In [537]:
X.dtypes

property_type       object
sector              object
bedRoom            float64
bathroom           float64
balcony             object
agePossession       object
built_up_area      float64
servant room       float64
store room         float64
furnishing_type     object
luxury_category     object
floor_category      object
dtype: object

In [ ]:
sorted(X['sector'].unique().tolist())

['dwarka expressway',
 'gwal pahari',
 'manesar',
 'sector 1',
 'sector 10',
 'sector 102',
 'sector 103',
 'sector 104',
 'sector 105',
 'sector 106',
 'sector 107',
 'sector 108',
 'sector 109',
 'sector 11',
 'sector 110',
 'sector 111',
 'sector 112',
 'sector 113',
 'sector 12',
 'sector 13',
 'sector 14',
 'sector 15',
 'sector 17',
 'sector 2',
 'sector 21',
 'sector 22',
 'sector 23',
 'sector 24',
 'sector 25',
 'sector 26',
 'sector 27',
 'sector 28',
 'sector 3',
 'sector 30',
 'sector 31',
 'sector 33',
 'sector 36',
 'sector 37',
 'sector 37d',
 'sector 38',
 'sector 39',
 'sector 4',
 'sector 40',
 'sector 41',
 'sector 43',
 'sector 45',
 'sector 46',
 'sector 47',
 'sector 48',
 'sector 49',
 'sector 5',
 'sector 50',
 'sector 51',
 'sector 52',
 'sector 53',
 'sector 54',
 'sector 55',
 'sector 56',
 'sector 57',
 'sector 58',
 'sector 59',
 'sector 6',
 'sector 60',
 'sector 61',
 'sector 62',
 'sector 63',
 'sector 63a',
 'sector 65',
 'sector 66',
 'sector 67',
 'sector 67a',
 'sector 68',
 'sector 69',
 'sector 7',
 'sector 70',
 'sector 70a',
 'sector 71',
 'sector 72',
 'sector 73',
 'sector 74',
 'sector 76',
 'sector 77',
 'sector 78',
 'sector 79',
 'sector 8',
 'sector 80',
 'sector 81',
 'sector 82',
 'sector 82a',
 'sector 83',
 'sector 84',
 'sector 85',
 'sector 86',
 'sector 88',
 'sector 88a',
 'sector 89',
 'sector 9',
 'sector 90',
 'sector 91',
 'sector 92',
 'sector 93',
 'sector 95',
 'sector 99',
 'sohna road']